
" :augroup numbertoggle
" :  autocmd!
" :  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
" :  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
" :augroup END

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" IDE Tools
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'https://github.com/kien/ctrlp.vim.git'

" Git
Plug 'tpope/vim-fugitive', {'statusline': '%{fugitive#statusline()}'}

" Syntax completion
Plug 'w0rp/ale'
Plug 'https://github.com/Quramy/tsuquyomi.git'

" Go
Plug 'fatih/vim-go'

call plug#end()

autocmd VimEnter * nmap <F3> :NERDTreeToggle<CR>
autocmd VimEnter * imap <F3> <Esc>:NERDTreeToggle<CR>
let g:ale_lint_on_text_changed = 'never'
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
autocmd VimEnter * map <silent> <C-u> :tabm -1<CR>
autocmd VimEnter * map <silent> <C-i> :tabm +1<CR>
" autocmd VimEnter * map <silent> <C-u> :tabp<CR>
" autocmd VimEnter * map <silent> <C-i> :tabn<CR>

" set IDE view
:set number
:set tabstop=4 shiftwidth=4
:set ignorecase
:set smartcase
:NERDTreeToggle

" omnicompletion
" always show menu
:set completeopt=longest,menuone
" trigger with . keypress
function! OpenCompletion()
	if !pumvisible() && v:char == '.'
		call feedkeys("\<C-x>\<C-o>", "n")
	endif
endfunction
autocmd InsertCharPre * call OpenCompletion()
